= AsciiDoc Keyboard Macros
:page-subtitle:
:page-tags: asciidoc keyboard macros
:description:
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Chords

For key combinations that mix chords (simultaneous presses) with sequential keys (common in editors like Emacs and Vim), separate each step into its own `kbd:[]` macro separated by a space.

[NOTE]
====
While the convention and recommendation is to represent alpha keys in uppercase, editors like Emacs and Vim are strictly case-sensitive, which means that in many key sequences, lowercase and uppercase will do something different.
In the examples below, literal keys that must be pressed without kbd:[Shift] are kept lowercase.
====

|===
|Shortcut |Purpose

|kbd:[Ctrl+X] kbd:[Ctrl+F]
|Emacs find file sequence (Two successive chords).

|kbd:[Ctrl+R] kbd:[f]
|Vim Insert mode sequence: Presses the kbd:[Ctrl+R] chord, followed by the literal lowercase kbd:[f] key to paste the contents of register `f`.
|===
