= Bundler (Ruby)
:page-subtitle:
:page-tags: ruby bundler
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Intro to bundler

* https://bundler.io/[Bundler official site].

== Error Could not find gem ’pry-doc

Consider this `Gemfile`:

[source,gemfile]
----
source 'https://rubygems.org'

gem 'pry'
gem 'pry-doc'
----

In the past (IIRC), we could run both `bundler` or `bundle` commands interchangeably:

[source,shell-session]
----
$ bundler install
$ bundle install
----

This is what I see on Jul 2022 with ruby 3.0.0 (installed through `rvm`) on my Arch Linux system:

....
$ ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

$ bundler --version
Bundler version 2.2.3

$ bundle --version
Bundler version 2.2.3

$ which bundler bundle
/home/devel/.rvm/rubies/ruby-3.0.0/bin/bundler
/home/devel/.rvm/rubies/ruby-3.0.0/bin/bundle

$ file "$(which bundle)" ; file "$(which bundler)"
/home/devel/.rvm/rubies/ruby-3.0.0/bin/bundle: Ruby script, ASCII text executable
/home/devel/.rvm/rubies/ruby-3.0.0/bin/bundler: Ruby script, ASCII text executable

$ du -h "$(which bundle)" ; du -h "$(which bundler)"
4.0K    /home/devel/.rvm/rubies/ruby-3.0.0/bin/bundle
4.0K    /home/devel/.rvm/rubies/ruby-3.0.0/bin/bundler
....

So, yeah, we are damn sure both `bundler` and `bundle` are the same
program. And yet this error showed up when using `bundler install`:

[source,shell-session]
----
$ bundler install
Could not find gem 'pry-doc x86_64-linux' in any of the gem sources
listed in your Gemfile.
----

Tried again with `bundle` (instead of `bundler`) and it worked 😲.
It is worth nothing that as of this writing, the docs only mention `bundle install` and not `bundler install`.

It is also worth nothing that later I could not reproduce this problem and `bundler install` worked too.

== Bundler version in Gemfile.lock

link:https://blog.rubygems.org/2022/01/23/bundler-v2-3[Bundler 2.3^] introduced a requirement that requires that the bundler version we are using on the command line match the version in `Gem.lock`:

[source,shell-session]
----
$ bundler install
Bundler 4.0.10 is running, but your lockfile was generated with
2.4.14. Installing Bundler 2.4.14 and restarting using that version.
----

The version is mentioned at the very end of `Gem.lock`.
E.g.:

.Excerpt from Gemfile.lock
[source,text]
----
BUNDLED WITH
   2.4.14
----

And it will use that version automtically, even if you restart your terminal session as soon as you enter the project directory where `Gemfile.lock` mentions that version.

== Update bundler version in Gemfile.lock

To update to a newer version of bundler in the lockfile, some tutorials recommend running `bundler update --bundler`.
That did not work for me, as it respectes whatever the version is already at the end of `Gemfile.lock`, or the version of bundler loaded in the current shell session.

There are at least two ways to update the bundler version for the project.
The more straightforward one is by specifying the target version in the `bundler update` command:

[source,shell-session]
----
$ bundler udpate --bundler=4.0.17
----


Another option is to let bundler choose whatever version you have by default (not the version in the project).
For example, if a new shell session in your `$HOME` directory has bundler 4.0.17 by default, it is possible to make the project version be changed to that version as well.
Follow these steps:

. Remove the `BUNDLED WITH` section from the end of `Gemfile.lock`.
. Start a new shell session so it doesn't inherit the old bundler version, but instead picks whatever bundler version is the default on your fresh, non-project shells.
. Run `bundler update --bundler` (without “=x.y.z” version).
. The `BUNDLED WITH` should now be back at the end of `Gemfile.lock` mentioning the new version.
